services:
  db:
    image: mysql:8.0 
    environment:
      MYSQL_DATABASE: flaskapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./db-data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  stream:
    build: stream-service
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=flaskapp
      - REDIS_HOST=redis
    volumes:
      - ./stream-service:/app
      - videos:/videos
    depends_on:
      - db
      - redis
  upload:
    build: upload-service
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=flaskapp
      - REDIS_HOST=redis
    volumes:
      - ./upload-service:/app
      - videos:/videos
    depends_on:
      - db
      - redis
  authentication:
    build: auth-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=flaskapp
      - REDIS_HOST=redis
    volumes:
      - ./auth-service:/app
    depends_on:
      - db
      - redis
volumes:
  videos: